### PR TITLE
map NProgress props on hoc

### LINKED ISSUE #83: When using hoc props are no longer passed
I have taken some time to research this one.
It looks like the release for fixing #4 also improved the way nprogress can be attached,which is just by using the hoc, no more need for adding the NProgress component, however configuring NProgress has been obfuscated.

It is no longer possible to overwrite the default Props of NProgress which remain the default: 
```
color: "#2299DD",
showAfterMs: 300,
spinner: true
```
also the property `delayMs` is misconfigured as it should be `showAfterMs`.

### PR DESCRIPTION
**Pull request by decebal**
should fix #83

### CODE REVIEW

**Comment by lapidus** [comment]
@sergiodxa: Great if this can be merged 👍

**Comment by martenbjork** [comment]
Confirmed as working. Great work, @decebal !

**Comment by decebal** [comment]
@martenbjork @sergiodxa I've solved the lock file conflicts and updated the PR. I have no write access so it's down to you guys to merge this.

**Comment by balazsnemeth** [comment]
@sergiodxa , @martenbjork , can you please Merge this? We really need this improvement 👍

**Comment by sergiodxa** [comment]
Hello,

I'm not maintaining this anymore because I'm not using it anymore in my projects and I don't have time to work on it.

Feel free to fork and publish to npm with another name.

**Pull request closed without merging**
