### PR TITLE
Use Next router events correctly (Fix #32)

### LINKED ISSUE #32: Cannot read property 'onRouteChangeStart' of undefined
Hey @sergiodxa - once I upgraded to 1.3.0 my app fails to run with this error:

```js
Uncaught TypeError: Cannot read property 'onRouteChangeStart' of undefined
    at b.i (component.js:formatted:1)
    at commitLifeCycles (react-dom.development.js:15255)
    at commitAllLifeCycles (react-dom.development.js:16523)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at commitRoot (react-dom.development.js:16677)
    at completeRoot (react-dom.development.js:18069)
    at performWorkOnRoot (react-dom.development.js:17997)
    at performWork (react-dom.development.js:17901)
    at performSyncWork (react-dom.development.js:17873)
    at requestWork (react-dom.development.js:17761)
    at scheduleWork (react-dom.development.js:17566)
    at scheduleRootUpdate (react-dom.development.js:18240)
    at updateContainerAtExpirationTime (react-dom.development.js:18267)
    at updateContainer (react-dom.development.js:18324)
    at ReactRoot.render (react-dom.development.js:18586)
    at eval (react-dom.development.js:18726)
    at unbatchedUpdates (react-dom.development.js:18124)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:18722)
    at Object.hydrate (react-dom.development.js:18780)
    at renderReactElement (index.js:334)
    at _callee5$ (index.js:397)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:288)
    at Generator.prototype.(:3000/anonymous function) [as next] (http://localhost:3000/_next/static/runtime/main.js:16427:21)
    at asyncGeneratorStep (asyncToGenerator.js:5)
    at _next (asyncToGenerator.js:27)
    at asyncToGenerator.js:34
    at new Promise (<anonymous>)
    at new F (_export.js:36)
    at asyncToGenerator.js:23
    at _doRender (index.js:457)
    at doRender (index.js:343)
    at _callee2$ (index.js:233)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:288)
    at Generator.prototype.(:3000/anonymous function) [as next] (http://localhost:3000/_next/static/runtime/main.js:16427:21)
    at asyncGeneratorStep (asyncToGenerator.js:5)
    at _next (asyncToGenerator.js:27)
    at asyncToGenerator.js:34
    at new Promise (<anonymous>)
    at new F (_export.js:36)
    at asyncToGenerator.js:23
    at _render (index.js:254)
    at render (index.js:205)
    at _callee$ (index.js:185)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:288)
    at Generator.prototype.(:3000/anonymous function) [as next] (http://localhost:3000/_next/static/runtime/main.js:16427:21)
```

This is in combination with React 16.6.

Here is a branch with repo: https://github.com/brianlovin/brian-lovin-next/tree/react-and-fixes
clone, yarn, and `yarn run dev` should repro this error. It appears the error likely came from https://github.com/sergiodxa/next-nprogress/pull/27/files but it's hard to say.

Curious if you've seen this (I couldn't find anything too similar in past issues). In the meantime I'm going to try and fork + fix a local version of this package.

### PR DESCRIPTION
**Pull request by jchapple**
We should bind to Next router events as documented [here](https://github.com/zeit/next.js/#router-events), rather than overriding callbacks.

Fixes #32

### CODE REVIEW

**Comment by revskill10** [comment]
All of current issues were fixed by my PR [here](https://github.com/sergiodxa/next-nprogress/pull/22) but for unknown reason, the author library closed it. I'm not sure why, but i hope before closing an issue, one should make a test first ?

**Comment by jchapple** [comment]
@revskill10 Your PR would not resolve these issues, not even issue #21, which it was supposed to address.

**Comment by jchapple** [comment]
This fix returns the library to a working state. I have tested it.

**Comment by sergiodxa** [comment]
Thanks! This is published as 1.4.0.

**Pull request merged**
